/* Carrete "lifestyle" de la portada: fotos + descripciones en el mismo orden.
   Vive aquí, y no dentro del componente, para que las descripciones se
   traduzcan y revisen junto al resto del contenido. */

export const REEL = [
  '/images/blue-cala-anchor.jpg',
  '/images/navan-5.jpg',
  '/images/blue-cave-paddle.jpg',
  '/images/navan-7.jpg',
  '/images/blue-helm-teak.jpg',
  '/images/navan-cannes-2.jpg',
  '/images/blue-platform-couple.jpg',
  '/images/navan-coast-run.jpg',
  '/images/blue-profile.jpg',
  '/images/navan-dji-1.jpg',
  '/images/life-4.jpg',
  '/images/blue-snorkel-split.jpg',
  '/images/navan-print-37.jpg',
  '/images/blue-townhouse.jpg',
  '/images/navan-rocks-cove.jpg',
  '/images/reel-beach-cove.jpg',
  '/images/blue-vertical.jpg',
  '/images/navan-sunset-run.jpg',
  '/images/reel-dolphin.jpg',
  '/images/reel-palms-beach.jpg',
  '/images/reel-navan-aerial.jpg',
  '/images/reel-wake-loop.jpg',
  '/images/reel-aerial-pair.jpg',
  '/images/reel-navan-anchored.jpg',
  '/images/reel-navan-cliff.jpg',
  '/images/reel-cockpit-bow.jpg',
  '/images/reel-navan-covrun.jpg',
  '/images/reel-cockpit-table.jpg',
  '/images/reel-navan-cruise.jpg',
  '/images/reel-cockpit-teak.jpg',
  '/images/reel-navan-friends.jpg',
  '/images/reel-engines-under.jpg',
  '/images/reel-navan-run.jpg',
  '/images/reel-feet-teak.jpg',
  '/images/reel-navan-stern.jpg',
  '/images/reel-sunpad-couple.jpg',
];

/* Descripción de cada foto, en el mismo orden que REEL — el patrón numerado
   ("Una vida en el mar 23") no dice nada a quien usa lector de pantalla. */
export const REEL_ALTS = [
  'La Sea Ray SPX 210 fondeada en una cala',
  'La NAVAN T30 navegando por la costa',
  'Paddle surf junto a una cueva marina',
  'La NAVAN T30 fondeada en aguas transparentes',
  'El puesto de mando de la SPX 210 sobre cubierta de teca',
  'La NAVAN T30 en la bahía',
  'Una pareja sentada en la plataforma de baño',
  'La NAVAN T30 navegando pegada a la costa',
  'Perfil de la SPX 210 navegando',
  'Vista aérea de la NAVAN T30 desde el dron',
  'Momento de descanso a bordo',
  'Foto partida: snorkel bajo el agua junto al barco',
  'La NAVAN T30 al sol del mediodía',
  'La SPX 210 frente a la fachada del puerto',
  'La NAVAN T30 entre rocas en una cala',
  'Cala de arena vista desde el agua',
  'La SPX 210 vista desde arriba',
  'La NAVAN T30 navegando al atardecer',
  'Delfines nadando junto al barco',
  'La playa de Puerto Banús entre palmeras',
  'Vista aérea de la NAVAN T30',
  'Estela circular del barco vista desde el aire',
  'Dos barcos del club fondeados, vistos desde el aire',
  'La NAVAN T30 fondeada en calma',
  'La NAVAN T30 bajo un acantilado',
  'La bañera y la proa vistas desde popa',
  'La NAVAN T30 saliendo de una cala',
  'La mesa de la bañera preparada',
  'La NAVAN T30 en travesía',
  'Detalle de la bañera con cubierta de teca',
  'Amigos a bordo de la NAVAN T30',
  'Los motores fueraborda vistos desde el agua',
  'La NAVAN T30 a plena velocidad',
  'Pies descalzos sobre la cubierta de teca',
  'La popa de la NAVAN T30',
  'Una pareja en el solárium de proa',
];
